channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - nodejs=14
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyter-lsp-r
  - python-lsp-server
  - json-lsp
  - yaml-lsp
  - r
  - r-irkernel
  - rpy2
  - flake8 >=3.5
  - pylint
  - texlab
  - pip
  - pip:
    - rich-cli