channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - nodejs=14
  - pip
  - pip:
    - rich-cli
    - calysto_bash
    - sshkernel
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyter-lsp-r
  - python-lsp-server
  - json-lsp
  - yaml-lsp
  - r  
  - rpy2
  - flake8
  - pylint
  - texlab
  - chktex
  - shellcheck
  - ipydrawio
  - ipydrawio-export