#!/usr/bin/env bash
set -eux

if [ "$NB_USER" = "dryam" ]; then
    mkdir -p $NB_PYTHON_PREFIX/share/jupyter/lab/settings/
    cp .binder/lsp-overrides.json $NB_PYTHON_PREFIX/share/jupyter/lab/settings/
fi

jlpm add --dev  \
    bash-language-server \
    dockerfile-language-server-nodejs \
    pyright \
    sql-language-server \
    typescript-language-server \
    unified-language-server \
    vscode-css-languageserver-bin \
    vscode-html-languageserver-bin \
    vscode-json-languageserver-bin \
    yaml-language-server
